import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laske
 */
public class UserSupport extends javax.swing.JFrame {
    
    public void LoadTable(){
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("User");
    modelo.addColumn("Password");
    modelo.addColumn("Status");

    for(User u : ListUser){
        modelo.addRow(new Object[]{
            u.getUsername(),
            u.getPassword(),
            u.Active() ? "Active" : "Inactive"
        });
    }

    TableUser.setModel(modelo);
}
    
    ArrayList<User> ListUser;
    String currentUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserSupport.class.getName());
    
    public UserSupport(ArrayList<User> ListUser, String currentUser){
        initComponents();
        this.ListUser = ListUser;
        this.currentUser = currentUser;
        LoadTable();
        validarPermisos();
    }
    private void validarPermisos(){

    if(!currentUser.equals("JorgeC")){

        AddUser.setEnabled(false);
        btnEdit.setEnabled(false);
        btnInactive.setEnabled(false);

        txtNewUser.setEnabled(false);
        txtNewPassword.setEnabled(false);
    }
}
    /**
     * Creates new form UserSupport

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewUser = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JPasswordField();
        AddUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInactive = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNewUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        txtNewPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        AddUser.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AddUser.setText("Add User");
        AddUser.addActionListener(this::AddUserActionPerformed);

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("New User");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("New Password");

        btnInactive.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnInactive.setText("Inactive User");
        btnInactive.addActionListener(this::btnInactiveActionPerformed);

        btnEdit.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnBack.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnBack.setText("Back to menu");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtNewUser)
                            .addComponent(txtNewPassword))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInactive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInactive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
    String user = txtNewUser.getText();
    String pass = new String(txtNewPassword.getPassword());

    if(user.isEmpty() || pass.isEmpty()){
        JOptionPane.showMessageDialog(this, "Empty Fields");
        return;
    }

    if(pass.length() < 13){
        JOptionPane.showMessageDialog(this, "Minimum 13 characters");
        return;
    }

    if(!pass.matches(".*[A-Z].*")){
        JOptionPane.showMessageDialog(this, "Must contain uppercase");
        return;
    }

    if(!pass.matches(".*[!@#$%^&*()].*")){
        JOptionPane.showMessageDialog(this, "Must contain special character");
        return;
    }

    for(User u : ListUser){
        if(u.getUsername().equals(user)){
            JOptionPane.showMessageDialog(this, "Existing User");
            return;
        }
    }

    ListUser.add(new User(user, pass));

    txtNewUser.setText("");
    txtNewPassword.setText("");

    LoadTable();

    JOptionPane.showMessageDialog(this, "User Successfully Registered");
      
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserActionPerformed

    private void btnInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactiveActionPerformed
     int fila = TableUser.getSelectedRow();

    if(fila >= 0){
        ListUser.get(fila).setActivo(false);
        LoadTable();

        JOptionPane.showMessageDialog(this, "User Inactive");
    } else {
        JOptionPane.showMessageDialog(this, "Select a User");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInactiveActionPerformed

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        int fila = TableUser.getSelectedRow();

        if(fila >= 0){
            txtNewUser.setText(ListUser.get(fila).getUsername());
            txtNewPassword.setText(ListUser.get(fila).getPassword());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_TableUserMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int fila = TableUser.getSelectedRow();

    if(fila >= 0){

        String user = txtNewUser.getText();
        String pass = new String(txtNewPassword.getPassword());

        if(user.isEmpty() || pass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Empty Fields");
            return;
        }

        for(int i = 0; i < ListUser.size(); i++){
            if(i != fila && ListUser.get(i).getUsername().equals(user)){
                JOptionPane.showMessageDialog(this, "Existing User");
                return;
            }
        }

        ListUser.get(fila).setUsername(user);
        ListUser.get(fila).setPassword(pass);

        txtNewUser.setText("");
        txtNewPassword.setText("");

        LoadTable();

        JOptionPane.showMessageDialog(this, "User Successfully Updated");

    } else {
        JOptionPane.showMessageDialog(this, "Select a User");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MenuPrincipal menu = new MenuPrincipal(ListUser, currentUser);
        menu.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new UserSupport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JTable TableUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInactive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtNewUser;
    // End of variables declaration//GEN-END:variables
}
